QueryFirstAsync、QuerySingleAsync実装
huurou/DbHelper pull request #7
Opened 2024-10-22 07:33 UTC by ronron1114

QueryFirstAsyncとQuerySingleAsyncを実装しました

2024-10-22 08:04 UTC, huurou commented on LibDbHelper/DbHelper.cs
ユニットテストも書いてください。
特にSingleは要素数が0個、1個、2個 それぞれのケースのテストが必要です。

2024-10-22 08:04 UTC, huurou commented on LibDbHelper/DbHelper.cs
> +                    var result = default(T);
カウンターを用意するのではなく、`if (await reader.ReadAsync(cancellationToken))`を2回呼ぶのはどうでしょう
1回目falseなら要素なし 2回目trueなら複数要素と判定できます。

2024-10-22 08:05 UTC, huurou commented on LibDbHelper/DbHelper.cs
> +                    {
カウンターを用意するのではなく、`if (await reader.ReadAsync(cancellationToken))`を2回呼ぶのはどうでしょう
1回目falseなら要素なし 2回目trueなら複数要素と判定できます。

2024-10-22 15:12 UTC, huurou requested changes
以下の変更をお願いします。
- 対象メソッドのテストコード追加
- QuerySingleAsyncの実装改善

2024-10-23 04:18 UTC, huurou requested changes
素晴らしいテストありがとうございます。
メソッド名に期待される結果を書くことで、テストコードのドキュメント化が促進されるので記載してほしいです。
例：QueryFirstAsync_結果セット0件のとき失敗
例：QueryFirstAsync_結果セット0件_InvalidOperationException発生

2024-10-23 04:22 UTC, ronron1114 commented
例1を採用してQueryFirstAsync_結果セット0件のとき失敗のように変更しました！

2024-10-23 04:43 UTC, huurou approved these changes
ｲｲﾈ! 👍

2024-10-23 04:43 UTC, merged